"""create computers table

Revision ID: 193fd880cb36
Revises: 
Create Date: 2026-08-07 15:26:46.273162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '193fd880cb36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('lab_name', sa.String(length=100), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_index(op.f('ix_computers_agent_id'), 'computers', ['agent_id'], unique=True)
    op.create_index(op.f('ix_computers_id'), 'computers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_computers_id'), table_name='computers')
    op.drop_index(op.f('ix_computers_agent_id'), table_name='computers')
    op.drop_table('computers')
    # ### end Alembic commands ###
